// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3360.Hyperion2014;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc3360.Hyperion2014.commands.AutonomousBackAndForth;
import org.usfirst.frc3360.Hyperion2014.commands.DriveTrain_MoveTo;
/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    public Joystick driverLeftJoystick;
    public Joystick driverRightJoystick;
    public Joystick coPilotJoystick;
    
    public JoystickButton Button_DriveTrain_MoveTo;  

    public JoystickButton Button_CanonShooter_Shoot;  
    
    public JoystickButton Button_CanonSpinner_SetManualMode;
    public JoystickButton Button_CanonSpinner_ShootSpeed;
    public JoystickButton Button_CanonSpinner_CatchSpeed;
    
    public JoystickButton Button_CanonAngle_SetManualMode;
    public JoystickButton Button_CanonAngle_ResetSecurity;
    public JoystickButton Button_CanonAngle_SetAutoAngle;

    public OI() {
        coPilotJoystick = new Joystick(3);        
        driverRightJoystick = new Joystick(2);        
        driverLeftJoystick = new Joystick(1);
        
        Button_DriveTrain_MoveTo = new JoystickButton(driverRightJoystick, 9);
        Button_DriveTrain_MoveTo.whenPressed(new DriveTrain_MoveTo(8));
    }
    
    public Joystick getDriverLeftJoystick() {
        return driverLeftJoystick;
    }
    public Joystick getDriverRightJoystick() {
        return driverRightJoystick;
    }
    public Joystick getCoPilotJoystick() {
        return coPilotJoystick;
    }
}
