// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3360.Hyperion2014.commands;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3360.Hyperion2014.Robot;
import org.usfirst.frc3360.Hyperion2014.subsystems.CanonAngle;

public class  CanonAngle_HandleManualMode extends Command {
    public CanonAngle_HandleManualMode() {
        requires(Robot.ms_canonAngle);
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.ms_canonAngle.AngleStop();
        Robot.ms_canonAngle.ResetSecurity();
        Robot.ms_canonAngle.EnableAngleMode();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        //System.out.println("angle manual 1");
        
        // Read the co-pilot throttle.
        double dbThrottleValue = DriverStation.getInstance().getAnalogIn(1);
        double dbAngleWanted = ((CanonAngle.ms_MAX_CANON_ANGLE_VALUE - CanonAngle.ms_MIN_CANON_ANGLE_VALUE) /
                                (CanonAngle.ms_MAX_THROTTLE_VALUE-CanonAngle.ms_MIN_THROTTLE_VALUE) *
                                dbThrottleValue) +
                               114;
                              
        Robot.ms_canonAngle.HandleAngleMode(dbAngleWanted);
        
        //System.out.println("angle manual 2");
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
        
        CommandExit();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        
        CommandExit();
    }
    
    private void CommandExit() {
        Robot.ms_canonAngle.DisableAngleMode();
    }
}
