// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3360.Hyperion2014.subsystems;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import org.usfirst.frc3360.Hyperion2014.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class CanonShooter extends Subsystem {
    DoubleSolenoid shooterSolenoid = RobotMap.ms_dsCanonShooter;
    
    double ShootTime = 0;
    final long pullBackTimeMs = 700;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        shooterSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    
    public void shootBall(){
        shooterSolenoid.set(DoubleSolenoid.Value.kForward);
        ShootTime = System.currentTimeMillis();    
    }
    
    public void returnhome(){
        shooterSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    
    public boolean IsFinishedShoot(){
        return (ShootTime + pullBackTimeMs) < System.currentTimeMillis();
    }
}
