// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3360.Hyperion2014.subsystems;
import edu.wpi.first.wpilibj.AnalogChannel;
import edu.wpi.first.wpilibj.SpeedController;
import org.usfirst.frc3360.Hyperion2014.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc3360.Hyperion2014.Robot;
/**
 *
 */
public class CanonSpinner extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController allWheelSpinnerMotor = RobotMap.canonSpinnerAllWheelSpinnerMotor;
    AnalogChannel leftWheelCurrentSensor = RobotMap.canonSpinnerLeftWheelCurrentSensor;
    AnalogChannel rightWheelCurrentSensor = RobotMap.canonSpinnerRightWheelCurrentSensor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    double catchSpeed = -0.45;
    double shootSpeed = 1;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.q
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void PrepareTopGoalShot(){
        allWheelSpinnerMotor.set(shootSpeed);
    }
    
    public void StopSpinning(){
        allWheelSpinnerMotor.set(0);
    }
    
    
    public void PrepareCatchSpin(){
        allWheelSpinnerMotor.set(catchSpeed);
    }
    
    
    public void HandleSpinnerManualMode(){
        catchSpeed = Robot.oi.getCoPilotJoystick().getRawAxis(3);
        shootSpeed = Robot.oi.getCoPilotJoystick().getRawAxis(4);
    }
    
    public void HandleSpinnerPresetMode(){
        catchSpeed = -0.45;
        shootSpeed = 1;
    }
            
}
