// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3360.Hyperion2014.subsystems;


import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc3360.Hyperion2014.RobotMap;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStationEnhancedIO;
import edu.wpi.first.wpilibj.Timer;

/**
 *
 */
public class LedsSetter extends Subsystem {
    
    Relay ColorLedsRelay = RobotMap.ColorLedsRelay;
    Relay FlashingLedsRelay = RobotMap.FlashingLedsRelay;
    double LastFlashTimeMs = System.currentTimeMillis();

   
    public void initDefaultCommand() {
        
    }
    
    
    public void FlashLedsPeriodic(){
        
        double flashTimeMs = 1;
        try {
            flashTimeMs = DriverStation.getInstance().getEnhancedIO().getAnalogIn(8) * 1000;
        } catch (DriverStationEnhancedIO.EnhancedIOException ex) {
            ex.printStackTrace();
        }
        
        System.out.println("FlashTime" + flashTimeMs);
        
        if (System.currentTimeMillis() - LastFlashTimeMs > flashTimeMs){
            
            FlashingLedsRelay.set(Relay.Value.kOff);
            Timer.delay(0.1);
            FlashingLedsRelay.set(Relay.Value.kForward);
            
            LastFlashTimeMs = System.currentTimeMillis();
        }
      
    }
    
    
    public void SetBumpersColor(){
        
        double ColorValue = DriverStation.getInstance().getAnalogIn(6);
        
        if(ColorValue > 1.5){
            
            ColorLedsRelay.set(Relay.Value.kForward);
        }
        else{
            ColorLedsRelay.set(Relay.Value.kReverse);
        }
        
    }
}